"""Add user admin approval fields

Revision ID: 0dceccd3d798
Revises: 2554acb395ee
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dceccd3d798'
down_revision = '2554acb395ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=False, server_default='0'))
    
    # Set first user (if exists) as admin and approved
    # This will be handled by application logic, but we set defaults
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###

