"""add_invoice_type_and_cif_fields

Revision ID: 23aca829d151
Revises: 651555801aed
Create Date: 2025-12-03 14:45:42.293252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23aca829d151'
down_revision = '651555801aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('invoice_type', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('cif_emitent', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('cif_beneficiar', sa.String(length=20), nullable=True))
    op.add_column('invoices', sa.Column('issuer_name', sa.String(length=200), nullable=True))
    op.add_column('invoices', sa.Column('receiver_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_invoices_cif_beneficiar'), 'invoices', ['cif_beneficiar'], unique=False)
    op.create_index(op.f('ix_invoices_cif_emitent'), 'invoices', ['cif_emitent'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_type'), 'invoices', ['invoice_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_invoice_type'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_cif_emitent'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_cif_beneficiar'), table_name='invoices')
    op.drop_column('invoices', 'receiver_name')
    op.drop_column('invoices', 'issuer_name')
    op.drop_column('invoices', 'cif_beneficiar')
    op.drop_column('invoices', 'cif_emitent')
    op.drop_column('invoices', 'invoice_type')
    # ### end Alembic commands ###

