"""Increase password_hash column size

Revision ID: 2554acb395ee
Revises: 7587afddb10d
Create Date: 2025-11-20 17:12:08.365596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2554acb395ee'
down_revision = '7587afddb10d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###

